apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  containers:
  - image: almalinux
    command: ["sleep", "1000"]
    name: almalinux
    volumeMounts:
    - mountPath: /mnt/nginx/logs
      name: nginx-logs    
      readOnly: true
  volumes:
  - name: nginx-logs
    # this creats the empty directory in rhe node where pod scheduled
    emptyDir:
      sizeLimit: 500Mi